In [22]:
from platform import python_version
python_version()

'3.6.13'

In [23]:
import os
os.getcwd()

'c:\\Users\\ankit19.gupta\\Desktop\\Self Projects\\7. Creating a Dataset and training an Artificial Neural Network with Keras'

In [3]:
## Usecase: Drug Vaccination between age 13-100 years
## people >65 yrs : observed some side effects
## people <65 yrs : no side effects

In [4]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import adam_v2

In [5]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [24]:
train_sample=[]
train_label=[]

In [25]:
for i in range(1000):
    younger_ages=randint(13,64)
    train_sample.append(younger_ages)
    train_label.append(0)

    older_ages=randint(65,100)
    train_sample.append(older_ages)
    train_label.append(1)

In [26]:
train_sample


[39,
 68,
 57,
 97,
 53,
 68,
 18,
 81,
 56,
 83,
 49,
 69,
 25,
 75,
 58,
 87,
 39,
 85,
 23,
 89,
 41,
 74,
 34,
 65,
 36,
 68,
 22,
 70,
 15,
 81,
 48,
 80,
 26,
 66,
 41,
 98,
 30,
 72,
 50,
 91,
 62,
 94,
 53,
 88,
 37,
 90,
 47,
 67,
 32,
 85,
 48,
 70,
 32,
 78,
 32,
 98,
 47,
 81,
 41,
 75,
 27,
 98,
 25,
 94,
 39,
 79,
 63,
 78,
 44,
 70,
 27,
 72,
 61,
 66,
 41,
 80,
 38,
 83,
 13,
 96,
 41,
 73,
 46,
 91,
 47,
 99,
 16,
 71,
 40,
 70,
 50,
 99,
 29,
 79,
 41,
 91,
 20,
 91,
 44,
 82,
 51,
 75,
 61,
 70,
 62,
 80,
 18,
 98,
 25,
 69,
 34,
 88,
 24,
 81,
 33,
 86,
 56,
 84,
 46,
 91,
 21,
 87,
 57,
 66,
 37,
 65,
 26,
 98,
 15,
 85,
 50,
 72,
 28,
 67,
 46,
 73,
 37,
 69,
 60,
 87,
 56,
 65,
 35,
 91,
 51,
 71,
 44,
 72,
 61,
 67,
 31,
 79,
 24,
 94,
 20,
 100,
 54,
 72,
 24,
 99,
 63,
 94,
 57,
 78,
 21,
 73,
 38,
 73,
 55,
 95,
 61,
 81,
 64,
 76,
 29,
 93,
 42,
 95,
 47,
 95,
 20,
 82,
 48,
 80,
 60,
 72,
 28,
 73,
 49,
 97,
 14,
 82,
 61,
 71,
 44,
 95,
 36,
 88,
 43,
 92,

In [27]:
train_label

[0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,


In [28]:
train_sample=np.array(train_sample)

In [29]:
train_label=np.array(train_label)

In [30]:
scaler=MinMaxScaler(feature_range=(0,1))

In [31]:
scaler_train_sample=scaler.fit_transform(train_sample.reshape(-1,1))

In [32]:
scaler_train_sample

array([[0.29885057],
       [0.63218391],
       [0.50574713],
       ...,
       [0.85057471],
       [0.4137931 ],
       [0.66666667]])

In [33]:
model=Sequential([Dense(16,input_dim=1,activation='relu'),Dense(32,activation='relu'),Dense(2,activation='softmax')])

In [34]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [35]:
from tensorflow.keras.optimizers import Adam

In [36]:
model.compile(Adam(lr=0.001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

c:\Users\ankit19.gupta\.conda\envs\Self_Projects\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [37]:
len(train_sample)

2000

In [38]:
len(train_label)

2000

In [39]:
model.fit(train_sample,train_label,batch_size=10,epochs=10)

Epoch 1/10
200/200 [==============================] - 0s 1ms/step - loss: 1.3126 - accuracy: 0.5205
Epoch 2/10
200/200 [==============================] - 0s 1ms/step - loss: 0.5525 - accuracy: 0.7100
Epoch 3/10
200/200 [==============================] - 0s 942us/step - loss: 0.4574 - accuracy: 0.8105
Epoch 4/10
200/200 [==============================] - 0s 1ms/step - loss: 0.3851 - accuracy: 0.8675
Epoch 5/10
200/200 [==============================] - 0s 1ms/step - loss: 0.3222 - accuracy: 0.9015
Epoch 6/10
200/200 [==============================] - 0s 1ms/step - loss: 0.2650 - accuracy: 0.9315
Epoch 7/10
200/200 [==============================] - 0s 1ms/step - loss: 0.2271 - accuracy: 0.9445
Epoch 8/10
200/200 [==============================] - 0s 1ms/step - loss: 0.1956 - accuracy: 0.9425
Epoch 9/10
200/200 [==============================] - 0s 920us/step - loss: 0.1672 - accuracy: 0.9585
Epoch 10/10
200/200 [==============================] - 0s 1ms/step - loss: 0.1533 - accuracy: 0.

In [40]:
test_sample=[]
test_label=[]

In [41]:
for i in range(500):
    younger_ages=randint(13,64)
    test_sample.append(younger_ages)
    test_label.append(0)

    older_ages=randint(65,100)
    test_sample.append(older_ages)
    test_label.append(1)

In [42]:
test_sample=np.array(test_sample)
test_label=np.array(test_label)

In [44]:
model.predict(test_sample,batch_size=10)

array([[0.77985364, 0.22014636],
       [0.2333669 , 0.7666331 ],
       [0.9763168 , 0.02368314],
       ...,
       [0.02933377, 0.9706662 ],
       [0.9524474 , 0.04755265],
       [0.31945002, 0.68055   ]], dtype=float32)

In [49]:
test_sample_output=(model.predict(test_sample) > 0.5).astype("int32")

In [68]:
test_output=[]
for i in range(len(test_sample_output)):
    test_output.append(test_sample_output[i][0])
test_output=np.array(test_output)

In [69]:
from sklearn.metrics import confusion_matrix
predictedvalues=confusion_matrix(test_label,test_output)

In [70]:
predictedvalues

array([[ 31, 469],
       [500,   0]], dtype=int64)